version: "3.8"
services:
  api:
    image: back
    ports:
      - "8080:8080"
    environment:
      - doodle.internalPadUrl=http://etherpad:9001/
      - doodle.externalPadUrl=http://etherpad:9001/
      - quarkus.datasource.jdbc.url=jdbc:mysql://db:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
    restart: always
  front:
    image: front
    hostname: front
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ../front/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../front/pad.conf:/etc/nginx/conf.d/pad.conf

  db:
    image: mysql
    hostname: db
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
  etherpad:
    image: etherpad/etherpad:latest
    hostname: etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    hostname: mail
    restart: always
    ports:
      - "2525:25"